# Generated by Django 5.2.2 on 2025-06-24 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25, unique=True)),
                ('email', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=25)),
                ('gold', models.BigIntegerField(blank=True)),
                ('is_active', models.BooleanField()),
                ('last_login', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Characters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('id_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='main.accounts')),
                ('id_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='main.classes')),
            ],
        ),
        migrations.CreateModel(
            name='Powers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
                ('description', models.TextField(null=True)),
                ('type', models.CharField(max_length=25)),
                ('id_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='powers', to='main.classes')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterPower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slots', models.PositiveSmallIntegerField(default=0)),
                ('character', models.ForeignKey(db_column='id_character', on_delete=django.db.models.deletion.CASCADE, to='main.characters')),
                ('power', models.ForeignKey(db_column='id_power', on_delete=django.db.models.deletion.CASCADE, to='main.powers')),
            ],
            options={
                'db_table': 'character_powers',
                'unique_together': {('character', 'power')},
            },
        ),
        migrations.CreateModel(
            name='AccountPower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateField()),
                ('account', models.ForeignKey(db_column='id_account', on_delete=django.db.models.deletion.CASCADE, to='main.accounts')),
                ('power', models.ForeignKey(db_column='id_power', on_delete=django.db.models.deletion.CASCADE, to='main.powers')),
            ],
            options={
                'db_table': 'account_powers',
                'unique_together': {('account', 'power')},
            },
        ),
    ]
