# Generated by Django 5.2.2 on 2025-06-24 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Levels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('completion_time', models.TimeField()),
                ('kill_amount', models.IntegerField(null=True)),
                ('character', models.ForeignKey(db_column='id_character', on_delete=django.db.models.deletion.CASCADE, to='main.characters')),
            ],
        ),
    ]
