# Generated by Django 5.2.2 on 2025-06-24 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_levels_character'),
    ]

    operations = [
        migrations.RenameField(
            model_name='characters',
            old_name='id_account',
            new_name='account',
        ),
        migrations.RenameField(
            model_name='powers',
            old_name='id_class',
            new_name='classe',
        ),
    ]
