name: Django Tests

# Run tests on every push and pull request
on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Get your code
    - name: Checkout code
      uses: actions/checkout@v4

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    # Step 3: Install Python dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install Django
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    # Step 4: Set up Django settings
    - name: Set environment variables
      run: |
        echo "SECRET_KEY='testing-key-012154'" >> $GITHUB_ENV
        echo "DEBUG=True" >> $GITHUB_ENV

    # Step 5: Check Django setup
    - name: Check Django setup
      run: python manage.py check

    # Step 6: Run database migrations
    - name: Run migrations
      run: |
        python manage.py makemigrations
        python manage.py migrate

    # Step 7: Run your tests
    - name: Run tests
      run: python manage.py test --verbosity=2

    # Step 8: Success message
    - name: Success
      if: success()
      run: echo "🎉 All tests passed!"