name: Django Tests


on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install Django==5.2.2
        pip install python-dotenv
        # Install from requirements.txt if it exists
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Set environment variables
      run: |
        echo "DJANGO_SETTINGS_MODULE=config.settings" >> $GITHUB_ENV
        echo "DEBUG=True" >> $GITHUB_ENV
        echo "CI=true" >> $GITHUB_ENV
        # These will be ignored since we're using CI=true
        echo "DB_NAME=dummy" >> $GITHUB_ENV
        echo "DB_USER=dummy" >> $GITHUB_ENV
        echo "DB_PASSWORD=dummy" >> $GITHUB_ENV
        echo "DB_HOST=dummy" >> $GITHUB_ENV

    - name: Check Django setup
      run: python manage.py check

    - name: Run migrations
      run: |
        python manage.py makemigrations
        python manage.py migrate

    - name: Run tests
      run: python manage.py test --verbosity=2

    - name: Success
      if: success()
      run: echo "🎉 All tests passed!"
